# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Peter Duncan
tagline:          'Automated Test System Developer'
description:      'Welcome! Crafted in Scotland by <a href="https://twitter.com/PeteDunc" target="_blank">@PeteDunc</a>.'
url:              http://pdunc.github.io
baseurl:          /

author:
  name:           'Peter Duncan'
  url:            https://twitter.com/PeteDunc

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/pdunc/pdunc.github.io
